### ISSUE TITLE
Project Naming Discussion

### ISSUE THREAD

**Issue by sillydan1** [sillydan1/AALTITOAD#2]
Leave your name suggestions down below. These are my ideas so far: 

- AALTITOAD (AAlborg TIck TOck Automata Debunker/Doublechecker/valiDator)
- TTAAAL (Tick Tock Automata AALborg)
- TAEBAAL - (Pronounced tea-ball) Ticktock Automata Engine By AALborg
- TETARVAAL (TTA Engine with Trace Abstraction Refinement Verification AALborg)
- TOTAAL (Tick tOck auTomata AALborg)

Or just something super boring such as 

- ttaverif
- verifytta

**Comment by tgm-git** [comment]
AALTI-TOAD is the superior option!

**Comment by sillydan1** [comment]
TickTaal

**Comment by sillydan1** [comment]
AALTITOAD is picked, and implemented. Closing this discussion.
